event:
  - id: 10
    name: 'E-STOP'
    animation:
      both:
        animation_name: slide
        duration: 3

  - id: 25
    name: 'TURN-LEFT'
    animation:
      front:
        animation_name: slide
        duration: 2
        wait_after_sequence: 0.5
        repeat: 2
        keep_state: True

      tail:
        animation_name: slide
        duration: 3
        keep_state: False


  - id: 21
    name: 'TURN-LEFAT'
    interrupting: True
    animation:
      both:
        animation_name: slide
        duration: 2


  - id: 2137
    name: 'SLIDE-FIVE'
    animation:
      both:
        animation_name: slide
        duration: 1
        wait_after_sequence: 0
        repeat: 2
        keep_state: True