event:
  - id: 1
    name: 'E-STOP'
    interrupting: true
    animation:
      both:
        image: blinker.png
        duration: 3
        keep_state: true

  - id: 2
    name: 'ERROR'
    interrupting: true
    animation:
      both:
        image: blinker.png
        duration: 3
        repeat: 2

  - id: 3
    name: 'GOAL_ARCHIVED'
    interrupting: True
    animation:
      both:
        image: blinker.png
        duration: 3
        repeat: 3


  - id: 4
    name: 'CRITICAL_BATTERY'
    interrupting: True
    animation:
      both:
        image: blinker.png
        duration: 2
        repeat: 2

  - id: 5
    name: 'LOW_BATTERY'
    animation:
      both:
        image: blinker.png
        duration: 2
        repeat: 2

  - id: 6
    name: 'SHOW_BATTERY'
    interrupting: True
    animation:
      both:
        animation_name: battery
        duration: 1.5
        repeat: 5

  - id: 7
    name: 'AUTONOMUS_ACTION'
    animation:
      both:
        image: blinker.png
        duration: 3
        keep_state: True

  - id: 8
    name: 'WEB_ACTION'
    animation:
      both:
        image: blinker.png
        duration: 3
        keep_state: True

  - id: 9
    name: 'READY'
    animation:
      both:
        image: blinker.png
        duration: 1
        keep_state: True

