event:
  - id: 10
    name: 'E-STOP'
    animation:
      both:
        image: blinker.png
        color: 0xFFFF00
        duration: 1
        repeat: 5
        keep_state: False

  - id: 25
    name: 'TURN-LEFT'
    interrupting: true
    animation:
      front:
        image: blinker.png
        duration: 10
        repeat: 1
        keep_state: False

      tail:
        image: blinker.png
        duration: 5
        keep_state: False


  - id: 21
    name: 'TURN-LEFAT'
    interrupting: True
    animation:
      both:
        animation_name: battery
        duration: 2


  - id: 22
    name: 'SLIDE-FIVE'
    animation:
      both:
        image: blinker.png
        duration: 1
        repeat: 2
        keep_state: True
