event:
  - id: 1
    name: 'E-STOP'
    interrupting: true
    animation:
      both:
        image: emergency.png
        duration: 3

  - id: 2
    name: 'ERROR'
    interrupting: true
    animation:
      both:
        image: error_occured.png
        duration: 3
        repeat: 2

  - id: 3
    name: 'GOAL_ARCHIVED'
    interrupting: True
    animation:
      both:
        image: goal_archived.png
        duration: 3
        repeat: 3


  - id: 4
    name: 'CRITICAL_BATTERY'
    interrupting: True
    animation:
      both:
        image: critical_battery.png
        duration: 2
        repeat: 2

  - id: 5
    name: 'LOW_BATTERY'
    animation:
      both:
        image: low_battery.png
        duration: 2
        repeat: 2

  - id: 6
    name: 'SHOW_BATTERY'
    interrupting: True
    animation:
      both:
        animation_name: battery
        duration: 1
        repeat: 5

  - id: 7
    name: 'AUTONOMOUS_ACTION'
    animation:
      both:
        image: autonomous_action.png
        duration: 3

  - id: 8
    name: 'MANUAL_ACTION'
    animation:
      both:
        image: joystick_web_ui.png
        duration: 3

  - id: 9
    name: 'READY'
    animation:
      both:
        image: ready.png
        duration: 1

