version: '3.4'

services:
  panther_lights:
    build:
      context: ./../../panther_lights_controller/platforms/panther_lights_controller_rpi_apa102
    container_name: panther_lights_controller
    privileged: true
    volumes:
      - /dev/gpiomem:/dev/gpiomem
      - /sys:/sys
      - type: bind
        source: ./../../panther_lights_controller/panther_lights_controller_base/panther_lights_controller
        target: /ros_ws/src/panther_lights_controller
      - type: bind
        source: ./../../panther_lights_controller/panther_lights_controller_base/husarion_msgs
        target: /ros_ws/src/husarion_msgs
    command: rosrun panther_lights_controller controller_node.py
