name: Build/Publish Docker Image 

on:
  push:
    branches:
      - 'lights_new'
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag that the image will be built with'
        required: true
        default: 'latest'
      branch:
        description: 'branch that will be used to build image'
        required: true
        default: 'main'
  
jobs:
  build_lights_controller:
    runs-on: ubuntu-18.04

    steps:
        
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Unit test
      run: |
        docker build -t panther-lights-controller:base \
          -f ./panther_lights_controller/panther_lights_controller_base/Dockerfile \
          ./panther_lights_controller/panther_lights_controller_base/
        docker run --rm panther-lights-controller:base python3 /ros_ws/src/panther_lights_controller/tests/config_import_test.py

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    
    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push base tag
      uses: docker/build-push-action@v2
      with:
        context: ./panther_lights_controller/panther_lights_controller_base
        file: ./panther_lights_controller/panther_lights_controller_base/Dockerfile
        platforms: linux/arm64, linux/amd64
        push: true
        tags: husarion/panther-lights-controller:noetic-base-latest
        cache-from: type=registry,ref=husarion/panther-lights-controller:noetic-base-latest
        cache-to: type=inline

    - name: Build and push plt-gui tag
      uses: docker/build-push-action@v2
      with:
        context: ./panther_lights_controller/platforms/panther_lights_controller_plt_gui
        file: ./panther_lights_controller/platforms/panther_lights_controller_plt_gui/Dockerfile
        platforms: linux/arm64, linux/amd64
        push: true
        tags: husarion/panther-lights-controller:noetic-plt-gui-latest
        cache-from: type=registry,ref=husarion/panther-lights-controller:noetic-plt-gui-latest
        cache-to: type=inline

    - name: Build and push rpi-apa102 tag
      uses: docker/build-push-action@v2
      with:
        context: ./panther_lights_controller/platforms/panther_lights_controller_rpi_apa102
        file: ./panther_lights_controller/platforms/panther_lights_controller_rpi_apa102/Dockerfile
        platforms: linux/arm64
        push: true
        tags: husarion/panther-lights-controller:noetic-rpi-apa102-latest
        cache-from: type=registry,ref=husarion/panther-lights-controller:noetic-rpi-apa102-latest
        cache-to: type=inline


  build_lights_scheduler:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push panther_lights_scheduler
        uses: docker/build-push-action@v2
        with:
          context: ./panther_lights_scheduler/panther_lights_scheduler
          file: ./panther_lights_scheduler/panther_lights_scheduler/Dockerfile
          platforms: linux/arm64, linux/amd64
          push: true
          tags: husarion/panther-lights-scheduler:noetic-latest
          cache-from: type=registry,ref=husarion/panther-lights-scheduler:noetic-latest
          cache-to: type=inline