name: Build/Publish Docker Image 

on:
  push:
    branches:
      - 'lights_new'
  
jobs:
  build_lights_controller:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    
    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and test image
      run: |
        docker build -t panther_lights_controller:base \
          -f ./panther_lights_controller/panther_lights_controller_base/Dockerfile \
          ./panther_lights_controller/panther_lights_controller_base/
        docker run --rm panther_lights_controller:base python3 /ros_ws/src/panther_lights_controller/tests/config_import_test.py
          
    - name: Build and push base tag
      uses: docker/build-push-action@v2
      with:
        context: ./panther_lights_controller/panther_lights_controller_base
        file: ./panther_lights_controller/panther_lights_controller_base/Dockerfile
        platforms: linux/arm64, linux/amd64, linux/arm/v7
        push: true
        tags: husarion/panther_lights_controller:base
        cache-from: type=registry,ref=husarion/panther_lights_controller:base
        cache-to: type=inline

    - name: Build and push panther_lights_controller:plt_gui
      uses: docker/build-push-action@v2
      with:
        context: ./panther_lights_controller/platforms/panther_lights_controller_plt_gui
        file: ./panther_lights_controller/platforms/panther_lights_controller_plt_gui/Dockerfile
        platforms: linux/arm64, linux/amd64, linux/arm/v7
        push: true
        tags: husarion/panther_lights_controller:plt_gui
        cache-from: type=registry,ref=husarion/panther_lights_controller:plt_gui
        cache-to: type=inline

    - name: Build and push panther_lights_controller:rpi_apa102
      uses: docker/build-push-action@v2
      with:
        context: ./panther_lights_controller/platforms/panther_lights_controller_rpi_apa102
        file: ./panther_lights_controller/platforms/panther_lights_controller_rpi_apa102/Dockerfile
        platforms: linux/arm64, linux/arm/v7
        push: true
        tags: husarion/panther_lights_controller:rpi_apa102
        cache-from: type=registry,ref=husarion/panther_lights_controller:rpi_apa102
        cache-to: type=inline


  build_lights_scheduler:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push panther_lights_scheduler
        uses: docker/build-push-action@v2
        with:
          context: ./panther_lights_scheduler/panther_lights_scheduler
          file: ./panther_lights_scheduler/panther_lights_scheduler/Dockerfile
          platforms: linux/arm64, linux/amd64, linux/arm/v7
          push: true
          tags: husarion/panther_lights_scheduler
          cache-from: type=registry,ref=husarion/panther_lights_scheduler
          cache-to: type=inline